version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - target: 5672
        published: 5672
      # for web interface:
      - target: 15672
        published: 15672
    networks:
      - shpotify-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/

  mariadb:
    image: mariadb:11
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql:Z 
    networks:
      - shpotify-net
    environment:
      MARIADB_ROOT_PASSWORD: root

  minio:
    image: minio/minio
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command: server /data --console-address ":9001"
    networks:
      - shpotify-net
    volumes:
      - minio-data:/data

  mc:  # to use manually: docker run -it --rm --net shpotify-net minio/mc --entrypoint=/bin/sh
    image: minio/mc
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://minio:9000 root rootroot;
      /usr/bin/mc mb myminio/sourcefiles;
      /usr/bin/mc anonymous set download myminio/sourcefiles;
      exit 0;
      "
    networks:
      - shpotify-net

  # backend:
  #   image: 127.0.0.1:5000/shpotify-backend
  #   environment:
  #     NODE_ENV: production
  #   networks:
  #     - shpotify-net


networks:
  shpotify-net:
    name: shpotify-net
    driver: overlay
    attachable: true

volumes:
  mariadb-data:
  rabbitmq-data:
  minio-data:

# secrets:
#   username:
#     file: secret.txt
#   password:
#     file: secret.txt
